/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "spi_master.v:1" *)
module spi_master(clk, en, rst, tx_en, rx_en, miso, address, data_out, sclk, cs_n, mosi, data_in, rx_valid);
  (* src = "spi_master.v:36" *)
  wire [7:0] _0000_;
  (* src = "spi_master.v:36" *)
  wire [7:0] _0001_;
  (* src = "spi_master.v:36" *)
  wire _0002_;
  (* src = "spi_master.v:36" *)
  wire [7:0] _0003_;
  (* src = "spi_master.v:36" *)
  wire _0004_;
  (* src = "spi_master.v:36" *)
  wire _0005_;
  (* src = "spi_master.v:36" *)
  wire [7:0] _0006_;
  (* src = "spi_master.v:36" *)
  wire _0007_;
  (* src = "spi_master.v:36" *)
  wire _0008_;
  (* src = "spi_master.v:36" *)
  wire _0009_;
  (* src = "spi_master.v:36" *)
  wire [15:0] _0010_;
  (* src = "spi_master.v:36" *)
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  (* src = "spi_master.v:34" *)
  wire CPHA;
  (* src = "spi_master.v:33" *)
  wire CPOL;
  (* src = "spi_master.v:11" *)
  input [7:0] address;
  (* src = "spi_master.v:21" *)
  reg [7:0] bit_count;
  (* src = "spi_master.v:5" *)
  input clk;
  (* src = "spi_master.v:20" *)
  reg [7:0] count;
  (* init = 1'h1 *)
  (* src = "spi_master.v:14" *)
  output cs_n;
  reg cs_n = 1'h1;
  (* init = 8'h00 *)
  (* src = "spi_master.v:16" *)
  output [7:0] data_in;
  reg [7:0] data_in = 8'h00;
  (* src = "spi_master.v:12" *)
  input [7:0] data_out;
  (* src = "spi_master.v:6" *)
  input en;
  (* src = "spi_master.v:31" *)
  reg is_write;
  (* src = "spi_master.v:10" *)
  input miso;
  (* init = 1'h0 *)
  (* src = "spi_master.v:15" *)
  output mosi;
  reg mosi = 1'h0;
  (* src = "spi_master.v:7" *)
  input rst;
  (* src = "spi_master.v:23" *)
  reg [7:0] rx_data;
  (* src = "spi_master.v:9" *)
  input rx_en;
  (* src = "spi_master.v:29" *)
  reg rx_en_reg;
  (* init = 1'h0 *)
  (* src = "spi_master.v:17" *)
  output rx_valid;
  reg rx_valid = 1'h0;
  (* init = 1'h0 *)
  (* src = "spi_master.v:13" *)
  output sclk;
  reg sclk = 1'h0;
  (* src = "spi_master.v:22" *)
  reg [15:0] tx_data;
  (* src = "spi_master.v:8" *)
  input tx_en;
  (* src = "spi_master.v:28" *)
  reg tx_en_reg;
  assign _0012_ = ~rst;
  assign _0013_ = ~is_write;
  assign _0014_ = ~en;
  assign _0015_ = rx_en_reg & ~(rx_en);
  assign _0016_ = ~_0015_;
  assign _0017_ = tx_en_reg & ~(tx_en);
  assign _0018_ = ~((_0016_ & is_write) | _0017_);
  assign _0019_ = cs_n ? _0018_ : _0013_;
  assign _0020_ = en ? _0019_ : _0013_;
  assign _0004_ = _0012_ & ~(_0020_);
  assign _0007_ = rx_en & ~(rst);
  assign _0011_ = tx_en & ~(rst);
  assign _0021_ = ~rx_data[0];
  assign _0022_ = ~miso;
  assign _0023_ = ~(bit_count[7] | bit_count[6]);
  assign _0024_ = bit_count[5] | bit_count[4];
  assign _0025_ = _0024_ | ~(_0023_);
  assign _0026_ = bit_count[2] | ~(bit_count[3]);
  assign _0027_ = bit_count[1] | ~(bit_count[0]);
  assign _0028_ = _0027_ | _0026_;
  assign _0029_ = _0028_ | _0025_;
  assign _0030_ = _0023_ & ~(_0024_);
  assign _0031_ = ~bit_count[1];
  assign _0032_ = ~bit_count[2];
  assign _0033_ = ~bit_count[3];
  assign _0034_ = ~((_0032_ & _0031_) | _0033_);
  assign _0035_ = _0030_ & ~(_0034_);
  assign _0036_ = ~((_0035_ & _0029_) | is_write);
  assign _0037_ = bit_count[5] | ~(bit_count[4]);
  assign _0038_ = _0023_ & ~(_0037_);
  assign _0039_ = bit_count[3] | bit_count[2];
  assign _0040_ = _0031_ & ~(_0039_);
  assign _0041_ = ~((_0040_ & _0038_) | _0030_);
  assign _0042_ = _0039_ | _0027_;
  assign _0043_ = _0038_ & ~(_0042_);
  assign _0044_ = _0043_ | _0041_;
  assign _0045_ = _0036_ & ~(_0044_);
  assign _0046_ = _0045_ ? _0022_ : _0021_;
  assign _0047_ = sclk ? _0021_ : _0046_;
  assign _0048_ = count[1] | ~(count[0]);
  assign _0049_ = count[3] | count[2];
  assign _0050_ = _0049_ | _0048_;
  assign _0051_ = count[5] | count[4];
  assign _0052_ = count[7] | count[6];
  assign _0053_ = _0052_ | _0051_;
  assign _0054_ = _0053_ | _0050_;
  assign _0055_ = _0054_ ? _0021_ : _0047_;
  assign _0056_ = _0015_ | _0021_;
  assign _0057_ = _0056_ | _0017_;
  assign _0058_ = cs_n ? _0057_ : _0055_;
  assign _0059_ = en ? _0058_ : _0021_;
  assign _0006_[0] = _0012_ & ~(_0059_);
  assign _0060_ = ~rx_data[1];
  assign _0061_ = _0045_ ? _0021_ : _0060_;
  assign _0062_ = sclk ? _0060_ : _0061_;
  assign _0063_ = _0054_ ? _0060_ : _0062_;
  assign _0064_ = _0015_ | _0060_;
  assign _0065_ = _0064_ | _0017_;
  assign _0066_ = cs_n ? _0065_ : _0063_;
  assign _0067_ = en ? _0066_ : _0060_;
  assign _0006_[1] = _0012_ & ~(_0067_);
  assign _0068_ = ~rx_data[2];
  assign _0069_ = _0045_ ? _0060_ : _0068_;
  assign _0070_ = sclk ? _0068_ : _0069_;
  assign _0071_ = _0054_ ? _0068_ : _0070_;
  assign _0072_ = _0015_ | _0068_;
  assign _0073_ = _0072_ | _0017_;
  assign _0074_ = cs_n ? _0073_ : _0071_;
  assign _0075_ = en ? _0074_ : _0068_;
  assign _0006_[2] = _0012_ & ~(_0075_);
  assign _0076_ = ~rx_data[3];
  assign _0077_ = _0045_ ? _0068_ : _0076_;
  assign _0078_ = sclk ? _0076_ : _0077_;
  assign _0079_ = _0054_ ? _0076_ : _0078_;
  assign _0080_ = _0015_ | _0076_;
  assign _0081_ = _0080_ | _0017_;
  assign _0082_ = cs_n ? _0081_ : _0079_;
  assign _0083_ = en ? _0082_ : _0076_;
  assign _0006_[3] = _0012_ & ~(_0083_);
  assign _0084_ = ~rx_data[4];
  assign _0085_ = _0045_ ? _0076_ : _0084_;
  assign _0086_ = sclk ? _0084_ : _0085_;
  assign _0087_ = _0054_ ? _0084_ : _0086_;
  assign _0088_ = _0015_ | _0084_;
  assign _0089_ = _0088_ | _0017_;
  assign _0090_ = cs_n ? _0089_ : _0087_;
  assign _0091_ = en ? _0090_ : _0084_;
  assign _0006_[4] = _0012_ & ~(_0091_);
  assign _0092_ = ~rx_data[5];
  assign _0093_ = _0045_ ? _0084_ : _0092_;
  assign _0094_ = sclk ? _0092_ : _0093_;
  assign _0095_ = _0054_ ? _0092_ : _0094_;
  assign _0096_ = _0015_ | _0092_;
  assign _0097_ = _0096_ | _0017_;
  assign _0098_ = cs_n ? _0097_ : _0095_;
  assign _0099_ = en ? _0098_ : _0092_;
  assign _0006_[5] = _0012_ & ~(_0099_);
  assign _0100_ = ~rx_data[6];
  assign _0101_ = _0045_ ? _0092_ : _0100_;
  assign _0102_ = sclk ? _0100_ : _0101_;
  assign _0103_ = _0054_ ? _0100_ : _0102_;
  assign _0104_ = _0015_ | _0100_;
  assign _0105_ = _0104_ | _0017_;
  assign _0106_ = cs_n ? _0105_ : _0103_;
  assign _0107_ = en ? _0106_ : _0100_;
  assign _0006_[6] = _0012_ & ~(_0107_);
  assign _0108_ = ~rx_data[7];
  assign _0109_ = _0045_ ? _0100_ : _0108_;
  assign _0110_ = sclk ? _0108_ : _0109_;
  assign _0111_ = _0054_ ? _0108_ : _0110_;
  assign _0112_ = _0015_ | _0108_;
  assign _0113_ = _0112_ | _0017_;
  assign _0114_ = cs_n ? _0113_ : _0111_;
  assign _0115_ = en ? _0114_ : _0108_;
  assign _0006_[7] = _0012_ & ~(_0115_);
  assign _0116_ = ~tx_data[0];
  assign _0117_ = ~sclk;
  assign _0118_ = bit_count[1] | bit_count[0];
  assign _0119_ = _0118_ | _0026_;
  assign _0120_ = ~((_0119_ & bit_count[3]) | _0025_);
  assign _0121_ = _0119_ | _0025_;
  assign _0122_ = ~((_0121_ & _0120_) | is_write);
  assign _0123_ = ~((_0122_ | _0044_) & tx_data[0]);
  assign _0124_ = sclk ? _0123_ : _0116_;
  assign _0125_ = _0054_ ? _0116_ : _0124_;
  assign _0126_ = ~data_out[0];
  assign _0127_ = _0015_ | _0116_;
  assign _0128_ = _0017_ ? _0126_ : _0127_;
  assign _0129_ = cs_n ? _0128_ : _0125_;
  assign _0130_ = en ? _0129_ : _0116_;
  assign _0010_[0] = _0012_ & ~(_0130_);
  assign _0131_ = ~tx_data[1];
  assign _0132_ = ~(_0118_ | _0026_);
  assign _0133_ = ~((_0132_ | _0033_) & _0030_);
  assign _0134_ = _0030_ & ~(_0119_);
  assign _0135_ = ~((_0134_ | _0133_) & _0013_);
  assign _0136_ = _0135_ ? _0116_ : _0131_;
  assign _0137_ = _0044_ ? _0131_ : _0136_;
  assign _0138_ = sclk ? _0137_ : _0131_;
  assign _0139_ = _0054_ ? _0131_ : _0138_;
  assign _0140_ = ~data_out[1];
  assign _0141_ = _0015_ | _0131_;
  assign _0142_ = _0017_ ? _0140_ : _0141_;
  assign _0143_ = cs_n ? _0142_ : _0139_;
  assign _0144_ = en ? _0143_ : _0131_;
  assign _0010_[1] = _0012_ & ~(_0144_);
  assign _0145_ = ~tx_data[2];
  assign _0146_ = _0135_ ? _0131_ : _0145_;
  assign _0147_ = _0044_ ? _0145_ : _0146_;
  assign _0148_ = sclk ? _0147_ : _0145_;
  assign _0149_ = _0054_ ? _0145_ : _0148_;
  assign _0150_ = ~data_out[2];
  assign _0151_ = _0015_ | _0145_;
  assign _0152_ = _0017_ ? _0150_ : _0151_;
  assign _0153_ = cs_n ? _0152_ : _0149_;
  assign _0154_ = en ? _0153_ : _0145_;
  assign _0010_[2] = _0012_ & ~(_0154_);
  assign _0155_ = ~tx_data[3];
  assign _0156_ = _0135_ ? _0145_ : _0155_;
  assign _0157_ = _0044_ ? _0155_ : _0156_;
  assign _0158_ = sclk ? _0157_ : _0155_;
  assign _0159_ = _0054_ ? _0155_ : _0158_;
  assign _0160_ = ~data_out[3];
  assign _0161_ = _0015_ | _0155_;
  assign _0162_ = _0017_ ? _0160_ : _0161_;
  assign _0163_ = cs_n ? _0162_ : _0159_;
  assign _0164_ = en ? _0163_ : _0155_;
  assign _0010_[3] = _0012_ & ~(_0164_);
  assign _0165_ = ~tx_data[4];
  assign _0166_ = _0135_ ? _0155_ : _0165_;
  assign _0167_ = _0044_ ? _0165_ : _0166_;
  assign _0168_ = sclk ? _0167_ : _0165_;
  assign _0169_ = _0054_ ? _0165_ : _0168_;
  assign _0170_ = ~data_out[4];
  assign _0171_ = _0015_ | _0165_;
  assign _0172_ = _0017_ ? _0170_ : _0171_;
  assign _0173_ = cs_n ? _0172_ : _0169_;
  assign _0174_ = en ? _0173_ : _0165_;
  assign _0010_[4] = _0012_ & ~(_0174_);
  assign _0175_ = ~tx_data[5];
  assign _0176_ = _0135_ ? _0165_ : _0175_;
  assign _0177_ = _0044_ ? _0175_ : _0176_;
  assign _0178_ = sclk ? _0177_ : _0175_;
  assign _0179_ = _0054_ ? _0175_ : _0178_;
  assign _0180_ = ~data_out[5];
  assign _0181_ = _0015_ | _0175_;
  assign _0182_ = _0017_ ? _0180_ : _0181_;
  assign _0183_ = cs_n ? _0182_ : _0179_;
  assign _0184_ = en ? _0183_ : _0175_;
  assign _0010_[5] = _0012_ & ~(_0184_);
  assign _0185_ = ~tx_data[6];
  assign _0186_ = _0135_ ? _0175_ : _0185_;
  assign _0187_ = _0044_ ? _0185_ : _0186_;
  assign _0188_ = sclk ? _0187_ : _0185_;
  assign _0189_ = _0054_ ? _0185_ : _0188_;
  assign _0190_ = ~data_out[6];
  assign _0191_ = _0015_ | _0185_;
  assign _0192_ = _0017_ ? _0190_ : _0191_;
  assign _0193_ = cs_n ? _0192_ : _0189_;
  assign _0194_ = en ? _0193_ : _0185_;
  assign _0010_[6] = _0012_ & ~(_0194_);
  assign _0195_ = ~tx_data[7];
  assign _0196_ = _0135_ ? _0185_ : _0195_;
  assign _0197_ = _0044_ ? _0195_ : _0196_;
  assign _0198_ = sclk ? _0197_ : _0195_;
  assign _0199_ = _0054_ ? _0195_ : _0198_;
  assign _0200_ = ~data_out[7];
  assign _0201_ = _0015_ | _0195_;
  assign _0202_ = _0017_ ? _0200_ : _0201_;
  assign _0203_ = cs_n ? _0202_ : _0199_;
  assign _0204_ = en ? _0203_ : _0195_;
  assign _0010_[7] = _0012_ & ~(_0204_);
  assign _0205_ = ~tx_data[8];
  assign _0206_ = _0135_ ? _0195_ : _0205_;
  assign _0207_ = _0044_ ? _0205_ : _0206_;
  assign _0208_ = sclk ? _0207_ : _0205_;
  assign _0209_ = _0054_ ? _0205_ : _0208_;
  assign _0210_ = ~address[0];
  assign _0211_ = _0015_ ? _0210_ : _0205_;
  assign _0212_ = _0017_ ? _0210_ : _0211_;
  assign _0213_ = cs_n ? _0212_ : _0209_;
  assign _0214_ = en ? _0213_ : _0205_;
  assign _0010_[8] = _0012_ & ~(_0214_);
  assign _0215_ = ~tx_data[9];
  assign _0216_ = _0135_ ? _0205_ : _0215_;
  assign _0217_ = _0044_ ? _0215_ : _0216_;
  assign _0218_ = sclk ? _0217_ : _0215_;
  assign _0219_ = _0054_ ? _0215_ : _0218_;
  assign _0220_ = ~address[1];
  assign _0221_ = _0015_ ? _0220_ : _0215_;
  assign _0222_ = _0017_ ? _0220_ : _0221_;
  assign _0223_ = cs_n ? _0222_ : _0219_;
  assign _0224_ = en ? _0223_ : _0215_;
  assign _0010_[9] = _0012_ & ~(_0224_);
  assign _0225_ = ~tx_data[10];
  assign _0226_ = _0135_ ? _0215_ : _0225_;
  assign _0227_ = _0044_ ? _0225_ : _0226_;
  assign _0228_ = sclk ? _0227_ : _0225_;
  assign _0229_ = _0054_ ? _0225_ : _0228_;
  assign _0230_ = ~address[2];
  assign _0231_ = _0015_ ? _0230_ : _0225_;
  assign _0232_ = _0017_ ? _0230_ : _0231_;
  assign _0233_ = cs_n ? _0232_ : _0229_;
  assign _0234_ = en ? _0233_ : _0225_;
  assign _0010_[10] = _0012_ & ~(_0234_);
  assign _0235_ = ~tx_data[11];
  assign _0236_ = _0135_ ? _0225_ : _0235_;
  assign _0237_ = _0044_ ? _0235_ : _0236_;
  assign _0238_ = sclk ? _0237_ : _0235_;
  assign _0239_ = _0054_ ? _0235_ : _0238_;
  assign _0240_ = ~address[3];
  assign _0241_ = _0015_ ? _0240_ : _0235_;
  assign _0242_ = _0017_ ? _0240_ : _0241_;
  assign _0243_ = cs_n ? _0242_ : _0239_;
  assign _0244_ = en ? _0243_ : _0235_;
  assign _0010_[11] = _0012_ & ~(_0244_);
  assign _0245_ = ~tx_data[12];
  assign _0246_ = _0135_ ? _0235_ : _0245_;
  assign _0247_ = _0044_ ? _0245_ : _0246_;
  assign _0248_ = sclk ? _0247_ : _0245_;
  assign _0249_ = _0054_ ? _0245_ : _0248_;
  assign _0250_ = ~address[4];
  assign _0251_ = _0015_ ? _0250_ : _0245_;
  assign _0252_ = _0017_ ? _0250_ : _0251_;
  assign _0253_ = cs_n ? _0252_ : _0249_;
  assign _0254_ = en ? _0253_ : _0245_;
  assign _0010_[12] = _0012_ & ~(_0254_);
  assign _0255_ = ~tx_data[13];
  assign _0256_ = _0135_ ? _0245_ : _0255_;
  assign _0257_ = _0044_ ? _0255_ : _0256_;
  assign _0258_ = sclk ? _0257_ : _0255_;
  assign _0259_ = _0054_ ? _0255_ : _0258_;
  assign _0260_ = ~address[5];
  assign _0261_ = _0015_ ? _0260_ : _0255_;
  assign _0262_ = _0017_ ? _0260_ : _0261_;
  assign _0263_ = cs_n ? _0262_ : _0259_;
  assign _0264_ = en ? _0263_ : _0255_;
  assign _0010_[13] = _0012_ & ~(_0264_);
  assign _0265_ = ~tx_data[14];
  assign _0266_ = _0135_ ? _0255_ : _0265_;
  assign _0267_ = _0044_ ? _0265_ : _0266_;
  assign _0268_ = sclk ? _0267_ : _0265_;
  assign _0269_ = _0054_ ? _0265_ : _0268_;
  assign _0270_ = ~address[6];
  assign _0271_ = _0015_ ? _0270_ : _0265_;
  assign _0272_ = _0017_ ? _0270_ : _0271_;
  assign _0273_ = cs_n ? _0272_ : _0269_;
  assign _0274_ = en ? _0273_ : _0265_;
  assign _0010_[14] = _0012_ & ~(_0274_);
  assign _0275_ = ~tx_data[15];
  assign _0276_ = _0135_ ? _0265_ : _0275_;
  assign _0277_ = _0044_ ? _0275_ : _0276_;
  assign _0278_ = sclk ? _0277_ : _0275_;
  assign _0279_ = _0054_ ? _0275_ : _0278_;
  assign _0280_ = ~address[7];
  assign _0281_ = _0015_ ? _0280_ : _0275_;
  assign _0282_ = _0017_ ? _0280_ : _0281_;
  assign _0283_ = cs_n ? _0282_ : _0279_;
  assign _0284_ = en ? _0283_ : _0275_;
  assign _0010_[15] = _0012_ & ~(_0284_);
  assign _0285_ = ~bit_count[0];
  assign _0286_ = bit_count[0] ^ sclk;
  assign _0287_ = _0054_ ? _0285_ : _0286_;
  assign _0288_ = _0015_ | _0285_;
  assign _0289_ = _0288_ | _0017_;
  assign _0290_ = cs_n ? _0289_ : _0287_;
  assign _0291_ = en ? _0290_ : _0285_;
  assign _0000_[0] = _0012_ & ~(_0291_);
  assign _0292_ = ~(bit_count[1] ^ bit_count[0]);
  assign _0293_ = sclk ? _0031_ : _0292_;
  assign _0294_ = _0054_ ? _0031_ : _0293_;
  assign _0295_ = _0015_ | _0031_;
  assign _0296_ = _0295_ | _0017_;
  assign _0297_ = cs_n ? _0296_ : _0294_;
  assign _0298_ = en ? _0297_ : _0031_;
  assign _0000_[1] = _0012_ & ~(_0298_);
  assign _0299_ = ~(bit_count[1] & bit_count[0]);
  assign _0300_ = _0299_ ^ bit_count[2];
  assign _0301_ = sclk ? _0032_ : _0300_;
  assign _0302_ = _0054_ ? _0032_ : _0301_;
  assign _0303_ = _0015_ | _0032_;
  assign _0304_ = _0303_ | _0017_;
  assign _0305_ = cs_n ? _0304_ : _0302_;
  assign _0306_ = en ? _0305_ : _0032_;
  assign _0000_[2] = _0012_ & ~(_0306_);
  assign _0307_ = bit_count[2] & ~(_0299_);
  assign _0308_ = _0307_ ^ _0033_;
  assign _0309_ = sclk ? _0033_ : _0308_;
  assign _0310_ = _0054_ ? _0033_ : _0309_;
  assign _0311_ = _0015_ | _0033_;
  assign _0312_ = _0311_ | _0017_;
  assign _0313_ = cs_n ? _0312_ : _0310_;
  assign _0314_ = en ? _0313_ : _0033_;
  assign _0000_[3] = _0012_ & ~(_0314_);
  assign _0315_ = ~bit_count[4];
  assign _0316_ = ~(bit_count[3] & bit_count[2]);
  assign _0317_ = _0316_ | _0299_;
  assign _0318_ = _0317_ ^ bit_count[4];
  assign _0319_ = sclk ? _0315_ : _0318_;
  assign _0320_ = _0054_ ? _0315_ : _0319_;
  assign _0321_ = _0015_ | _0315_;
  assign _0322_ = _0321_ | _0017_;
  assign _0323_ = cs_n ? _0322_ : _0320_;
  assign _0324_ = en ? _0323_ : _0315_;
  assign _0000_[4] = _0012_ & ~(_0324_);
  assign _0325_ = ~bit_count[5];
  assign _0326_ = bit_count[4] & ~(_0317_);
  assign _0327_ = _0326_ ^ _0325_;
  assign _0328_ = sclk ? _0325_ : _0327_;
  assign _0329_ = _0054_ ? _0325_ : _0328_;
  assign _0330_ = _0015_ | _0325_;
  assign _0331_ = _0330_ | _0017_;
  assign _0332_ = cs_n ? _0331_ : _0329_;
  assign _0333_ = en ? _0332_ : _0325_;
  assign _0000_[5] = _0012_ & ~(_0333_);
  assign _0334_ = ~bit_count[6];
  assign _0335_ = ~(bit_count[5] & bit_count[4]);
  assign _0336_ = _0335_ | _0317_;
  assign _0337_ = _0336_ ^ bit_count[6];
  assign _0338_ = sclk ? _0334_ : _0337_;
  assign _0339_ = _0054_ ? _0334_ : _0338_;
  assign _0340_ = _0015_ | _0334_;
  assign _0341_ = _0340_ | _0017_;
  assign _0342_ = cs_n ? _0341_ : _0339_;
  assign _0343_ = en ? _0342_ : _0334_;
  assign _0000_[6] = _0012_ & ~(_0343_);
  assign _0344_ = ~bit_count[7];
  assign _0345_ = bit_count[6] & ~(_0336_);
  assign _0346_ = _0345_ ^ _0344_;
  assign _0347_ = sclk ? _0344_ : _0346_;
  assign _0348_ = _0054_ ? _0344_ : _0347_;
  assign _0349_ = _0015_ | _0344_;
  assign _0350_ = _0349_ | _0017_;
  assign _0351_ = cs_n ? _0350_ : _0348_;
  assign _0352_ = en ? _0351_ : _0344_;
  assign _0000_[7] = _0012_ & ~(_0352_);
  assign _0353_ = ~count[0];
  assign _0354_ = ~(_0054_ & _0353_);
  assign _0355_ = _0015_ | _0353_;
  assign _0356_ = _0355_ | _0017_;
  assign _0357_ = cs_n ? _0356_ : _0354_;
  assign _0358_ = en ? _0357_ : _0353_;
  assign _0001_[0] = _0012_ & ~(_0358_);
  assign _0359_ = ~count[1];
  assign _0360_ = count[0] ^ count[1];
  assign _0361_ = ~(_0360_ & _0054_);
  assign _0362_ = _0015_ | _0359_;
  assign _0363_ = _0362_ | _0017_;
  assign _0364_ = cs_n ? _0363_ : _0361_;
  assign _0365_ = en ? _0364_ : _0359_;
  assign _0001_[1] = _0012_ & ~(_0365_);
  assign _0366_ = ~count[2];
  assign _0367_ = count[0] & count[1];
  assign _0368_ = _0367_ ^ count[2];
  assign _0369_ = ~(_0368_ & _0054_);
  assign _0370_ = _0015_ | _0366_;
  assign _0371_ = _0370_ | _0017_;
  assign _0372_ = cs_n ? _0371_ : _0369_;
  assign _0373_ = en ? _0372_ : _0366_;
  assign _0001_[2] = _0012_ & ~(_0373_);
  assign _0374_ = ~count[3];
  assign _0375_ = _0367_ & ~(_0366_);
  assign _0376_ = _0375_ ^ _0374_;
  assign _0377_ = _0376_ | ~(_0054_);
  assign _0378_ = _0015_ | _0374_;
  assign _0379_ = _0378_ | _0017_;
  assign _0380_ = cs_n ? _0379_ : _0377_;
  assign _0381_ = en ? _0380_ : _0374_;
  assign _0001_[3] = _0012_ & ~(_0381_);
  assign _0382_ = ~count[4];
  assign _0383_ = ~(count[3] & count[2]);
  assign _0384_ = _0367_ & ~(_0383_);
  assign _0385_ = _0384_ ^ _0382_;
  assign _0386_ = _0385_ | ~(_0054_);
  assign _0387_ = _0015_ | _0382_;
  assign _0388_ = _0387_ | _0017_;
  assign _0389_ = cs_n ? _0388_ : _0386_;
  assign _0390_ = en ? _0389_ : _0382_;
  assign _0001_[4] = _0012_ & ~(_0390_);
  assign _0391_ = ~count[5];
  assign _0392_ = _0384_ & ~(_0382_);
  assign _0393_ = _0392_ ^ _0391_;
  assign _0394_ = _0393_ | ~(_0054_);
  assign _0395_ = _0015_ | _0391_;
  assign _0396_ = _0395_ | _0017_;
  assign _0397_ = cs_n ? _0396_ : _0394_;
  assign _0398_ = en ? _0397_ : _0391_;
  assign _0001_[5] = _0012_ & ~(_0398_);
  assign _0399_ = ~count[6];
  assign _0400_ = count[5] & count[4];
  assign _0401_ = ~(_0400_ & _0384_);
  assign _0402_ = _0401_ ^ count[6];
  assign _0403_ = _0402_ | ~(_0054_);
  assign _0404_ = _0015_ | _0399_;
  assign _0405_ = _0404_ | _0017_;
  assign _0406_ = cs_n ? _0405_ : _0403_;
  assign _0407_ = en ? _0406_ : _0399_;
  assign _0001_[6] = _0012_ & ~(_0407_);
  assign _0408_ = ~count[7];
  assign _0409_ = count[6] & ~(_0401_);
  assign _0410_ = _0409_ ^ _0408_;
  assign _0411_ = _0410_ | ~(_0054_);
  assign _0412_ = _0015_ | _0408_;
  assign _0413_ = _0412_ | _0017_;
  assign _0414_ = cs_n ? _0413_ : _0411_;
  assign _0415_ = en ? _0414_ : _0408_;
  assign _0001_[7] = _0012_ & ~(_0415_);
  assign _0416_ = ~(_0044_ & _0013_);
  assign _0417_ = _0416_ | _0117_;
  assign _0418_ = _0417_ | _0054_;
  assign _0419_ = _0418_ | cs_n;
  assign _0420_ = _0419_ | _0014_;
  assign _0008_ = _0012_ & ~(_0420_);
  assign _0421_ = ~data_in[0];
  assign _0422_ = is_write ? _0421_ : _0021_;
  assign _0423_ = _0044_ ? _0422_ : _0421_;
  assign _0424_ = sclk ? _0423_ : _0421_;
  assign _0425_ = _0054_ ? _0421_ : _0424_;
  assign _0426_ = cs_n ? _0421_ : _0425_;
  assign _0427_ = en ? _0426_ : _0421_;
  assign _0003_[0] = _0012_ & ~(_0427_);
  assign _0428_ = ~data_in[1];
  assign _0429_ = is_write ? _0428_ : _0060_;
  assign _0430_ = _0044_ ? _0429_ : _0428_;
  assign _0431_ = sclk ? _0430_ : _0428_;
  assign _0432_ = _0054_ ? _0428_ : _0431_;
  assign _0433_ = cs_n ? _0428_ : _0432_;
  assign _0434_ = en ? _0433_ : _0428_;
  assign _0003_[1] = _0012_ & ~(_0434_);
  assign _0435_ = ~data_in[2];
  assign _0436_ = is_write ? _0435_ : _0068_;
  assign _0437_ = _0044_ ? _0436_ : _0435_;
  assign _0438_ = sclk ? _0437_ : _0435_;
  assign _0439_ = _0054_ ? _0435_ : _0438_;
  assign _0440_ = cs_n ? _0435_ : _0439_;
  assign _0441_ = en ? _0440_ : _0435_;
  assign _0003_[2] = _0012_ & ~(_0441_);
  assign _0442_ = ~data_in[3];
  assign _0443_ = is_write ? _0442_ : _0076_;
  assign _0444_ = _0044_ ? _0443_ : _0442_;
  assign _0445_ = sclk ? _0444_ : _0442_;
  assign _0446_ = _0054_ ? _0442_ : _0445_;
  assign _0447_ = cs_n ? _0442_ : _0446_;
  assign _0448_ = en ? _0447_ : _0442_;
  assign _0003_[3] = _0012_ & ~(_0448_);
  assign _0449_ = ~data_in[4];
  assign _0450_ = is_write ? _0449_ : _0084_;
  assign _0451_ = _0044_ ? _0450_ : _0449_;
  assign _0452_ = sclk ? _0451_ : _0449_;
  assign _0453_ = _0054_ ? _0449_ : _0452_;
  assign _0454_ = cs_n ? _0449_ : _0453_;
  assign _0455_ = en ? _0454_ : _0449_;
  assign _0003_[4] = _0012_ & ~(_0455_);
  assign _0456_ = ~data_in[5];
  assign _0457_ = is_write ? _0456_ : _0092_;
  assign _0458_ = _0044_ ? _0457_ : _0456_;
  assign _0459_ = sclk ? _0458_ : _0456_;
  assign _0460_ = _0054_ ? _0456_ : _0459_;
  assign _0461_ = cs_n ? _0456_ : _0460_;
  assign _0462_ = en ? _0461_ : _0456_;
  assign _0003_[5] = _0012_ & ~(_0462_);
  assign _0463_ = ~data_in[6];
  assign _0464_ = is_write ? _0463_ : _0100_;
  assign _0465_ = _0044_ ? _0464_ : _0463_;
  assign _0466_ = sclk ? _0465_ : _0463_;
  assign _0467_ = _0054_ ? _0463_ : _0466_;
  assign _0468_ = cs_n ? _0463_ : _0467_;
  assign _0469_ = en ? _0468_ : _0463_;
  assign _0003_[6] = _0012_ & ~(_0469_);
  assign _0470_ = ~data_in[7];
  assign _0471_ = is_write ? _0470_ : _0108_;
  assign _0472_ = _0044_ ? _0471_ : _0470_;
  assign _0473_ = sclk ? _0472_ : _0470_;
  assign _0474_ = _0054_ ? _0470_ : _0473_;
  assign _0475_ = cs_n ? _0470_ : _0474_;
  assign _0476_ = en ? _0475_ : _0470_;
  assign _0003_[7] = _0012_ & ~(_0476_);
  assign _0477_ = ~mosi;
  assign _0478_ = _0122_ | _0275_;
  assign _0479_ = _0478_ | _0044_;
  assign _0480_ = sclk ? _0479_ : _0477_;
  assign _0481_ = _0054_ ? _0477_ : _0480_;
  assign _0482_ = ~((_0016_ & mosi) | _0017_);
  assign _0483_ = cs_n ? _0482_ : _0481_;
  assign _0484_ = _0483_ | _0014_;
  assign _0005_ = _0012_ & ~(_0484_);
  assign _0485_ = _0117_ & ~(_0044_);
  assign _0486_ = sclk & ~(_0485_);
  assign _0487_ = _0054_ ? _0117_ : _0486_;
  assign _0488_ = _0015_ | _0117_;
  assign _0489_ = _0488_ | _0017_;
  assign _0490_ = cs_n ? _0489_ : _0487_;
  assign _0491_ = _0490_ | _0014_;
  assign _0009_ = _0012_ & ~(_0491_);
  assign _0492_ = ~(_0044_ & sclk);
  assign _0493_ = ~(_0492_ | _0054_);
  assign _0494_ = ~(_0017_ | _0015_);
  assign _0495_ = cs_n ? _0494_ : _0493_;
  assign _0496_ = _0495_ | _0014_;
  assign _0002_ = _0496_ | rst;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      sclk <= _0009_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      cs_n <= _0002_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      mosi <= _0005_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[0] <= _0003_[0];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[1] <= _0003_[1];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[2] <= _0003_[2];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[3] <= _0003_[3];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[4] <= _0003_[4];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[5] <= _0003_[5];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[6] <= _0003_[6];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      data_in[7] <= _0003_[7];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_valid <= _0008_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[0] <= _0001_[0];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[1] <= _0001_[1];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[2] <= _0001_[2];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[3] <= _0001_[3];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[4] <= _0001_[4];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[5] <= _0001_[5];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[6] <= _0001_[6];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      count[7] <= _0001_[7];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[0] <= _0000_[0];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[1] <= _0000_[1];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[2] <= _0000_[2];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[3] <= _0000_[3];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[4] <= _0000_[4];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[5] <= _0000_[5];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[6] <= _0000_[6];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      bit_count[7] <= _0000_[7];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[0] <= _0010_[0];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[1] <= _0010_[1];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[2] <= _0010_[2];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[3] <= _0010_[3];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[4] <= _0010_[4];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[5] <= _0010_[5];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[6] <= _0010_[6];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[7] <= _0010_[7];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[8] <= _0010_[8];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[9] <= _0010_[9];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[10] <= _0010_[10];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[11] <= _0010_[11];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[12] <= _0010_[12];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[13] <= _0010_[13];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[14] <= _0010_[14];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_data[15] <= _0010_[15];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[0] <= _0006_[0];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[1] <= _0006_[1];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[2] <= _0006_[2];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[3] <= _0006_[3];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[4] <= _0006_[4];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[5] <= _0006_[5];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[6] <= _0006_[6];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_data[7] <= _0006_[7];
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      tx_en_reg <= _0011_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      rx_en_reg <= _0007_;
  (* src = "spi_master.v:36" *)
  always @(posedge clk)
      is_write <= _0004_;
  assign CPHA = 1'h0;
  assign CPOL = 1'h0;
endmodule
