/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "spi_slave.v:1" *)
module spi_slave(rst, cs_n, sclk, mosi, miso, address, data_out);
  (* src = "spi_slave.v:36" *)
  wire [7:0] _000_;
  (* src = "spi_slave.v:36" *)
  (* unused_bits = "7" *)
  wire [7:0] _001_;
  (* src = "spi_slave.v:36" *)
  wire [7:0] _002_;
  (* src = "spi_slave.v:36" *)
  wire [7:0] _003_;
  (* src = "spi_slave.v:36" *)
  wire _004_;
  (* src = "spi_slave.v:36" *)
  wire _005_;
  (* src = "spi_slave.v:36" *)
  (* unused_bits = "7" *)
  wire [7:0] _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  (* init = 8'h00 *)
  (* src = "spi_slave.v:10" *)
  output [7:0] address;
  reg [7:0] address = 8'h00;
  (* src = "spi_slave.v:19" *)
  (* unused_bits = "7" *)
  wire [7:0] address_shift;
  (* src = "spi_slave.v:16" *)
  reg [7:0] bit_count;
  (* src = "spi_slave.v:6" *)
  input cs_n;
  (* init = 8'h00 *)
  (* src = "spi_slave.v:11" *)
  output [7:0] data_out;
  reg [7:0] data_out = 8'h00;
  (* src = "spi_slave.v:9" *)
  output miso;
  (* src = "spi_slave.v:23" *)
  reg miso_reg;
  (* src = "spi_slave.v:8" *)
  input mosi;
  (* src = "spi_slave.v:5" *)
  input rst;
  (* src = "spi_slave.v:17" *)
  reg rw;
  (* src = "spi_slave.v:20" *)
  (* unused_bits = "7" *)
  wire [7:0] rx_data;
  (* src = "spi_slave.v:7" *)
  input sclk;
  (* src = "spi_slave.v:21" *)
  wire [7:0] tx_data;
  assign _039_ = cs_n | rst;
  assign _040_ = ~rst;
  assign _041_ = ~cs_n;
  assign _031_ = ~((data_out[0] | _041_) & _040_);
  assign _032_ = ~((data_out[1] | _041_) & _040_);
  assign _033_ = ~((data_out[2] | _041_) & _040_);
  assign _034_ = ~((data_out[3] | _041_) & _040_);
  assign _035_ = ~((data_out[4] | _041_) & _040_);
  assign _036_ = ~((data_out[5] | _041_) & _040_);
  assign _037_ = ~((data_out[6] | _041_) & _040_);
  assign _038_ = ~((data_out[7] | _041_) & _040_);
  assign _042_ = ~(data_out[0] & cs_n);
  assign _015_ = _040_ & ~(_042_);
  assign _043_ = ~(data_out[1] & cs_n);
  assign _016_ = _040_ & ~(_043_);
  assign _044_ = ~(data_out[2] & cs_n);
  assign _017_ = _040_ & ~(_044_);
  assign _045_ = ~(data_out[3] & cs_n);
  assign _018_ = _040_ & ~(_045_);
  assign _046_ = ~(data_out[4] & cs_n);
  assign _019_ = _040_ & ~(_046_);
  assign _047_ = ~(data_out[5] & cs_n);
  assign _020_ = _040_ & ~(_047_);
  assign _048_ = ~(data_out[6] & cs_n);
  assign _021_ = _040_ & ~(_048_);
  assign _049_ = ~(data_out[7] & cs_n);
  assign _022_ = _040_ & ~(_049_);
  assign _023_ = ~((address[0] | _041_) & _040_);
  assign _024_ = ~((address[1] | _041_) & _040_);
  assign _025_ = ~((address[2] | _041_) & _040_);
  assign _026_ = ~((address[3] | _041_) & _040_);
  assign _027_ = ~((address[4] | _041_) & _040_);
  assign _028_ = ~((address[5] | _041_) & _040_);
  assign _029_ = ~((address[6] | _041_) & _040_);
  assign _030_ = ~((address[7] | _041_) & _040_);
  assign _050_ = ~(address[0] & cs_n);
  assign _007_ = _040_ & ~(_050_);
  assign _051_ = ~(address[1] & cs_n);
  assign _008_ = _040_ & ~(_051_);
  assign _052_ = ~(address[2] & cs_n);
  assign _009_ = _040_ & ~(_052_);
  assign _053_ = ~(address[3] & cs_n);
  assign _010_ = _040_ & ~(_053_);
  assign _054_ = ~(address[4] & cs_n);
  assign _011_ = _040_ & ~(_054_);
  assign _055_ = ~(address[5] & cs_n);
  assign _012_ = _040_ & ~(_055_);
  assign _056_ = ~(address[6] & cs_n);
  assign _013_ = _040_ & ~(_056_);
  assign _057_ = ~(address[7] & cs_n);
  assign _014_ = _040_ & ~(_057_);
  assign _058_ = bit_count[7] | bit_count[6];
  assign _059_ = bit_count[5] | bit_count[4];
  assign _060_ = ~(_059_ | _058_);
  assign _061_ = bit_count[1] | bit_count[0];
  assign _062_ = bit_count[3] | bit_count[2];
  assign _063_ = _062_ | _061_;
  assign _064_ = _060_ & ~(_063_);
  assign _065_ = bit_count[1] | ~(bit_count[0]);
  assign _066_ = ~(_065_ | _062_);
  assign _067_ = _062_ | bit_count[1];
  assign _068_ = _067_ | ~(_060_);
  assign _069_ = ~((_066_ & _060_) | _068_);
  assign _070_ = ~bit_count[3];
  assign _071_ = bit_count[2] | ~(bit_count[3]);
  assign _072_ = ~(_071_ | _061_);
  assign _073_ = ~((_072_ | _070_) & _060_);
  assign _074_ = ~(_073_ | _069_);
  assign _075_ = ~(_072_ & _060_);
  assign _076_ = _075_ ? address[0] : mosi;
  assign _077_ = _074_ ? _076_ : address[0];
  assign _000_[0] = _064_ ? address[0] : _077_;
  assign _078_ = _075_ ? address[1] : address_shift[0];
  assign _079_ = _074_ ? _078_ : address[1];
  assign _000_[1] = _064_ ? address[1] : _079_;
  assign _080_ = _075_ ? address[2] : address_shift[1];
  assign _081_ = _074_ ? _080_ : address[2];
  assign _000_[2] = _064_ ? address[2] : _081_;
  assign _082_ = _075_ ? address[3] : address_shift[2];
  assign _083_ = _074_ ? _082_ : address[3];
  assign _000_[3] = _064_ ? address[3] : _083_;
  assign _084_ = _075_ ? address[4] : address_shift[3];
  assign _085_ = _074_ ? _084_ : address[4];
  assign _000_[4] = _064_ ? address[4] : _085_;
  assign _086_ = _075_ ? address[5] : address_shift[4];
  assign _087_ = _074_ ? _086_ : address[5];
  assign _000_[5] = _064_ ? address[5] : _087_;
  assign _088_ = _075_ ? address[6] : address_shift[5];
  assign _089_ = _074_ ? _088_ : address[6];
  assign _000_[6] = _064_ ? address[6] : _089_;
  assign _090_ = _075_ ? address[7] : address_shift[6];
  assign _091_ = _074_ ? _090_ : address[7];
  assign _000_[7] = _064_ ? address[7] : _091_;
  assign _092_ = _071_ | _065_;
  assign _093_ = _060_ & ~(_092_);
  assign _094_ = ~bit_count[1];
  assign _095_ = ~bit_count[2];
  assign _096_ = ~((_095_ & _094_) | _070_);
  assign _097_ = _096_ | ~(_060_);
  assign _098_ = ~((_097_ | _093_) & rw);
  assign _099_ = bit_count[5] | ~(bit_count[4]);
  assign _100_ = _099_ | _058_;
  assign _101_ = _100_ | _063_;
  assign _102_ = ~(_101_ & _060_);
  assign _103_ = ~((_102_ & _101_) | _098_);
  assign _104_ = _101_ ? data_out[0] : mosi;
  assign _105_ = _103_ ? _104_ : data_out[0];
  assign _106_ = _074_ ? data_out[0] : _105_;
  assign _003_[0] = _064_ ? data_out[0] : _106_;
  assign _107_ = _101_ ? data_out[1] : rx_data[0];
  assign _108_ = _103_ ? _107_ : data_out[1];
  assign _109_ = _074_ ? data_out[1] : _108_;
  assign _003_[1] = _064_ ? data_out[1] : _109_;
  assign _110_ = _101_ ? data_out[2] : rx_data[1];
  assign _111_ = _103_ ? _110_ : data_out[2];
  assign _112_ = _074_ ? data_out[2] : _111_;
  assign _003_[2] = _064_ ? data_out[2] : _112_;
  assign _113_ = _101_ ? data_out[3] : rx_data[2];
  assign _114_ = _103_ ? _113_ : data_out[3];
  assign _115_ = _074_ ? data_out[3] : _114_;
  assign _003_[3] = _064_ ? data_out[3] : _115_;
  assign _116_ = _101_ ? data_out[4] : rx_data[3];
  assign _117_ = _103_ ? _116_ : data_out[4];
  assign _118_ = _074_ ? data_out[4] : _117_;
  assign _003_[4] = _064_ ? data_out[4] : _118_;
  assign _119_ = _101_ ? data_out[5] : rx_data[4];
  assign _120_ = _103_ ? _119_ : data_out[5];
  assign _121_ = _074_ ? data_out[5] : _120_;
  assign _003_[5] = _064_ ? data_out[5] : _121_;
  assign _122_ = _101_ ? data_out[6] : rx_data[5];
  assign _123_ = _103_ ? _122_ : data_out[6];
  assign _124_ = _074_ ? data_out[6] : _123_;
  assign _003_[6] = _064_ ? data_out[6] : _124_;
  assign _125_ = _101_ ? data_out[7] : rx_data[6];
  assign _126_ = _103_ ? _125_ : data_out[7];
  assign _127_ = _074_ ? data_out[7] : _126_;
  assign _003_[7] = _064_ ? data_out[7] : _127_;
  assign _128_ = _103_ ? mosi : rx_data[0];
  assign _129_ = _074_ ? rx_data[0] : _128_;
  assign _006_[0] = _064_ ? rx_data[0] : _129_;
  assign _130_ = _103_ ? rx_data[0] : rx_data[1];
  assign _131_ = _074_ ? rx_data[1] : _130_;
  assign _006_[1] = _064_ ? rx_data[1] : _131_;
  assign _132_ = _103_ ? rx_data[1] : rx_data[2];
  assign _133_ = _074_ ? rx_data[2] : _132_;
  assign _006_[2] = _064_ ? rx_data[2] : _133_;
  assign _134_ = _103_ ? rx_data[2] : rx_data[3];
  assign _135_ = _074_ ? rx_data[3] : _134_;
  assign _006_[3] = _064_ ? rx_data[3] : _135_;
  assign _136_ = _103_ ? rx_data[3] : rx_data[4];
  assign _137_ = _074_ ? rx_data[4] : _136_;
  assign _006_[4] = _064_ ? rx_data[4] : _137_;
  assign _138_ = _103_ ? rx_data[4] : rx_data[5];
  assign _139_ = _074_ ? rx_data[5] : _138_;
  assign _006_[5] = _064_ ? rx_data[5] : _139_;
  assign _140_ = _103_ ? rx_data[5] : rx_data[6];
  assign _141_ = _074_ ? rx_data[6] : _140_;
  assign _006_[6] = _064_ ? rx_data[6] : _141_;
  assign _142_ = _074_ ? mosi : address_shift[0];
  assign _001_[0] = _064_ ? address_shift[0] : _142_;
  assign _143_ = _074_ ? address_shift[0] : address_shift[1];
  assign _001_[1] = _064_ ? address_shift[1] : _143_;
  assign _144_ = _074_ ? address_shift[1] : address_shift[2];
  assign _001_[2] = _064_ ? address_shift[2] : _144_;
  assign _145_ = _074_ ? address_shift[2] : address_shift[3];
  assign _001_[3] = _064_ ? address_shift[3] : _145_;
  assign _146_ = _074_ ? address_shift[3] : address_shift[4];
  assign _001_[4] = _064_ ? address_shift[4] : _146_;
  assign _147_ = _074_ ? address_shift[4] : address_shift[5];
  assign _001_[5] = _064_ ? address_shift[5] : _147_;
  assign _148_ = _074_ ? address_shift[5] : address_shift[6];
  assign _001_[6] = _064_ ? address_shift[6] : _148_;
  assign _005_ = _064_ ? mosi : rw;
  assign _149_ = ~rw;
  assign _150_ = ~((_097_ | _093_) & _149_);
  assign _151_ = _150_ | _102_;
  assign _002_[0] = ~bit_count[0];
  assign _152_ = bit_count[4] | ~(bit_count[3]);
  assign _153_ = _152_ | _095_;
  assign _154_ = _094_ & ~(_153_);
  assign _155_ = bit_count[1] & ~(_153_);
  assign _156_ = _155_ | _154_;
  assign _157_ = _152_ | bit_count[2];
  assign _158_ = _094_ & ~(_157_);
  assign _159_ = bit_count[1] & ~(_157_);
  assign _160_ = _159_ | _158_;
  assign _161_ = bit_count[0] ? _160_ : _156_;
  assign _162_ = _151_ ? miso_reg : _161_;
  assign _163_ = _103_ ? miso_reg : _162_;
  assign _164_ = miso_reg & rw;
  assign _165_ = _075_ ? miso_reg : _164_;
  assign _166_ = _074_ ? _165_ : _163_;
  assign _004_ = _064_ ? miso_reg : _166_;
  assign _002_[1] = bit_count[1] ^ bit_count[0];
  assign _167_ = ~(bit_count[1] & bit_count[0]);
  assign _002_[2] = _167_ ^ _095_;
  assign _168_ = bit_count[2] & ~(_167_);
  assign _002_[3] = _168_ ^ bit_count[3];
  assign _169_ = ~(bit_count[3] & bit_count[2]);
  assign _170_ = _169_ | _167_;
  assign _002_[4] = ~(_170_ ^ bit_count[4]);
  assign _171_ = bit_count[4] & ~(_170_);
  assign _002_[5] = _171_ ^ bit_count[5];
  assign _172_ = ~(bit_count[5] & bit_count[4]);
  assign _173_ = _172_ | _170_;
  assign _002_[6] = ~(_173_ ^ bit_count[6]);
  assign _174_ = bit_count[6] & ~(_173_);
  assign _002_[7] = _174_ ^ bit_count[7];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _015_ or posedge _031_)
    if (_031_)
      data_out[0] <= 0;
    else if (_015_)
      data_out[0] <= 1;
    else
      data_out[0] <= _003_[0];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _016_ or posedge _032_)
    if (_032_)
      data_out[1] <= 0;
    else if (_016_)
      data_out[1] <= 1;
    else
      data_out[1] <= _003_[1];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _017_ or posedge _033_)
    if (_033_)
      data_out[2] <= 0;
    else if (_017_)
      data_out[2] <= 1;
    else
      data_out[2] <= _003_[2];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _018_ or posedge _034_)
    if (_034_)
      data_out[3] <= 0;
    else if (_018_)
      data_out[3] <= 1;
    else
      data_out[3] <= _003_[3];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _019_ or posedge _035_)
    if (_035_)
      data_out[4] <= 0;
    else if (_019_)
      data_out[4] <= 1;
    else
      data_out[4] <= _003_[4];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _020_ or posedge _036_)
    if (_036_)
      data_out[5] <= 0;
    else if (_020_)
      data_out[5] <= 1;
    else
      data_out[5] <= _003_[5];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _021_ or posedge _037_)
    if (_037_)
      data_out[6] <= 0;
    else if (_021_)
      data_out[6] <= 1;
    else
      data_out[6] <= _003_[6];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _022_ or posedge _038_)
    if (_038_)
      data_out[7] <= 0;
    else if (_022_)
      data_out[7] <= 1;
    else
      data_out[7] <= _003_[7];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _007_ or posedge _023_)
    if (_023_)
      address[0] <= 0;
    else if (_007_)
      address[0] <= 1;
    else
      address[0] <= _000_[0];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _008_ or posedge _024_)
    if (_024_)
      address[1] <= 0;
    else if (_008_)
      address[1] <= 1;
    else
      address[1] <= _000_[1];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _009_ or posedge _025_)
    if (_025_)
      address[2] <= 0;
    else if (_009_)
      address[2] <= 1;
    else
      address[2] <= _000_[2];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _010_ or posedge _026_)
    if (_026_)
      address[3] <= 0;
    else if (_010_)
      address[3] <= 1;
    else
      address[3] <= _000_[3];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _011_ or posedge _027_)
    if (_027_)
      address[4] <= 0;
    else if (_011_)
      address[4] <= 1;
    else
      address[4] <= _000_[4];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _012_ or posedge _028_)
    if (_028_)
      address[5] <= 0;
    else if (_012_)
      address[5] <= 1;
    else
      address[5] <= _000_[5];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _013_ or posedge _029_)
    if (_029_)
      address[6] <= 0;
    else if (_013_)
      address[6] <= 1;
    else
      address[6] <= _000_[6];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _014_ or posedge _030_)
    if (_030_)
      address[7] <= 0;
    else if (_014_)
      address[7] <= 1;
    else
      address[7] <= _000_[7];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      miso_reg <= 0;
    else
      miso_reg <= _004_;
  reg \address_shift_reg[0] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[0]  <= 0;
    else
      \address_shift_reg[0]  <= _001_[0];
  assign address_shift[0] = \address_shift_reg[0] ;
  reg \address_shift_reg[1] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[1]  <= 0;
    else
      \address_shift_reg[1]  <= _001_[1];
  assign address_shift[1] = \address_shift_reg[1] ;
  reg \address_shift_reg[2] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[2]  <= 0;
    else
      \address_shift_reg[2]  <= _001_[2];
  assign address_shift[2] = \address_shift_reg[2] ;
  reg \address_shift_reg[3] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[3]  <= 0;
    else
      \address_shift_reg[3]  <= _001_[3];
  assign address_shift[3] = \address_shift_reg[3] ;
  reg \address_shift_reg[4] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[4]  <= 0;
    else
      \address_shift_reg[4]  <= _001_[4];
  assign address_shift[4] = \address_shift_reg[4] ;
  reg \address_shift_reg[5] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[5]  <= 0;
    else
      \address_shift_reg[5]  <= _001_[5];
  assign address_shift[5] = \address_shift_reg[5] ;
  reg \address_shift_reg[6] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \address_shift_reg[6]  <= 0;
    else
      \address_shift_reg[6]  <= _001_[6];
  assign address_shift[6] = \address_shift_reg[6] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      rw <= 0;
    else
      rw <= _005_;
  reg \rx_data_reg[0] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[0]  <= 0;
    else
      \rx_data_reg[0]  <= _006_[0];
  assign rx_data[0] = \rx_data_reg[0] ;
  reg \rx_data_reg[1] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[1]  <= 0;
    else
      \rx_data_reg[1]  <= _006_[1];
  assign rx_data[1] = \rx_data_reg[1] ;
  reg \rx_data_reg[2] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[2]  <= 0;
    else
      \rx_data_reg[2]  <= _006_[2];
  assign rx_data[2] = \rx_data_reg[2] ;
  reg \rx_data_reg[3] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[3]  <= 0;
    else
      \rx_data_reg[3]  <= _006_[3];
  assign rx_data[3] = \rx_data_reg[3] ;
  reg \rx_data_reg[4] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[4]  <= 0;
    else
      \rx_data_reg[4]  <= _006_[4];
  assign rx_data[4] = \rx_data_reg[4] ;
  reg \rx_data_reg[5] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[5]  <= 0;
    else
      \rx_data_reg[5]  <= _006_[5];
  assign rx_data[5] = \rx_data_reg[5] ;
  reg \rx_data_reg[6] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      \rx_data_reg[6]  <= 0;
    else
      \rx_data_reg[6]  <= _006_[6];
  assign rx_data[6] = \rx_data_reg[6] ;
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[0] <= 0;
    else
      bit_count[0] <= _002_[0];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[1] <= 0;
    else
      bit_count[1] <= _002_[1];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[2] <= 0;
    else
      bit_count[2] <= _002_[2];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[3] <= 0;
    else
      bit_count[3] <= _002_[3];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[4] <= 0;
    else
      bit_count[4] <= _002_[4];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[5] <= 0;
    else
      bit_count[5] <= _002_[5];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[6] <= 0;
    else
      bit_count[6] <= _002_[6];
  (* src = "spi_slave.v:36" *)
  always @(posedge sclk or posedge _039_)
    if (_039_)
      bit_count[7] <= 0;
    else
      bit_count[7] <= _002_[7];
  assign miso = miso_reg;
  assign tx_data = 8'h5a;
endmodule
